all_crops = [
    # --- PART 1: CEREALS & GRAINS ---
    {"Crop": "Wheat", "Type": "Cereal", "Season": "Rabi", "N-P-K": "120:60:40", "Fertilizer": "Urea, DAP, MOP", "Soil": "Loamy", "Water": "Moderate", "Pest": "Aphids/Rust", "Harvesting": "March-April", "Pro-Tip": "Provide irrigation at the CRI (Crown Root Initiation) stage for max yield."},
    {"Crop": "Rice (Paddy)", "Type": "Cereal", "Season": "Kharif", "N-P-K": "100:60:40", "Fertilizer": "Zinc Sulphate, Urea, DAP", "Soil": "Clayey", "Water": "High", "Pest": "Stem Borer", "Harvesting": "Nov-Dec", "Pro-Tip": "Maintain 2-5cm of standing water during the tillering stage."},
    {"Crop": "Maize (Corn)", "Type": "Cereal", "Season": "Kharif/Rabi", "N-P-K": "120:60:40", "Fertilizer": "Urea, DAP, Zinc", "Soil": "Red/Loamy", "Water": "Moderate", "Pest": "Fall Armyworm", "Harvesting": "Sept-Oct", "Pro-Tip": "Apply Nitrogen in 3 split doses: Sowing, Knee-high, and Tasseling stages."},
    {"Crop": "Barley", "Type": "Cereal", "Season": "Rabi", "N-P-K": "60:30:20", "Fertilizer": "Urea, DAP, MOP", "Soil": "Sandy to Heavy", "Water": "Moderate", "Pest": "Nematode", "Harvesting": "March-April", "Pro-Tip": "Barley is more salt-tolerant than wheat, making it ideal for saline soils."},
    {"Crop": "Oats", "Type": "Cereal/Fodder", "Season": "Rabi", "N-P-K": "80:40:0", "Fertilizer": "Urea, SSP", "Soil": "Loamy", "Water": "Moderate", "Pest": "Aphids", "Harvesting": "120-150 Days", "Pro-Tip": "Harvest at the 'Dough stage' for the best quality fodder."},
    
    # --- PART 2: PULSES & LEGUMES ---
    {"Crop": "Chickpea (Gram)", "Type": "Pulse", "Season": "Rabi", "N-P-K": "20:60:20", "Fertilizer": "DAP, MOP", "Soil": "Heavy Soil", "Water": "Low", "Pest": "Pod Borer", "Harvesting": "Feb-April", "Pro-Tip": "Nipping (plucking top branches) at 50 days encourages more branching."},
    {"Crop": "Arhar (Pigeon Pea)", "Type": "Pulse", "Season": "Kharif", "N-P-K": "20:50:20", "Fertilizer": "DAP, Sulphur", "Soil": "Well-drained Alluvial", "Water": "Low", "Pest": "Pod Fly", "Harvesting": "Jan-March", "Pro-Tip": "Very sensitive to waterlogging; ensure fields have excellent drainage."},
    {"Crop": "Moong (Green Gram)", "Type": "Pulse", "Season": "Summer/Kharif", "N-P-K": "20:40:20", "Fertilizer": "DAP, MOP", "Soil": "Sandy Loam", "Water": "Low", "Pest": "Yellow Mosaic", "Harvesting": "65-75 Days", "Pro-Tip": "Pick mature pods in rounds to prevent shattering of early seeds."},
    {"Crop": "Black Gram (Urad)", "Type": "Pulse", "Season": "Kharif/Summer", "N-P-K": "20:40:20", "Fertilizer": "DAP, MOP", "Soil": "Loamy/Black", "Water": "Low", "Pest": "Hairy Caterpillar", "Harvesting": "75-90 Days", "Pro-Tip": "Seed treatment with Rhizobium increases yield by 15%."},
    {"Crop": "Lentil (Masoor)", "Type": "Pulse", "Season": "Rabi", "N-P-K": "20:40:20", "Fertilizer": "DAP, MOP", "Soil": "Alluvial", "Water": "Low", "Pest": "Aphids", "Harvesting": "Feb-March", "Pro-Tip": "Light irrigation at pod-filling significantly improves grain size."},
    
    # --- PART 3: OILSEEDS ---
    {"Crop": "Mustard", "Type": "Oilseed", "Season": "Rabi", "N-P-K": "80:40:40", "Fertilizer": "SSP, Urea, MOP", "Soil": "Sandy Loam", "Water": "Low", "Pest": "Mustard Aphid", "Harvesting": "Feb-March", "Pro-Tip": "Adding Sulphur (via SSP) significantly increases oil content."},
    {"Crop": "Groundnut", "Type": "Oilseed", "Season": "Kharif", "N-P-K": "20:40:40", "Fertilizer": "Gypsum, SSP, DAP", "Soil": "Sandy", "Water": "Moderate", "Pest": "White Grub", "Harvesting": "Oct-Nov", "Pro-Tip": "Apply Gypsum at pegging stage (45 days) for better pod development."},
    {"Crop": "Soybean", "Type": "Oilseed", "Season": "Kharif", "N-P-K": "20:60:40", "Fertilizer": "DAP, MOP, Sulphur", "Soil": "Black Soil", "Water": "Moderate", "Pest": "Girdle Beetle", "Harvesting": "Sept-Oct", "Pro-Tip": "Rhizobium culture is essential for nitrogen fixation."},
    {"Crop": "Sunflower", "Type": "Oilseed", "Season": "Year-round", "N-P-K": "60:80:40", "Fertilizer": "Urea, SSP, Boron", "Soil": "Deep Loamy", "Water": "Moderate", "Pest": "Head Borer", "Harvesting": "90-100 Days", "Pro-Tip": "Hand pollination improves seed setting significantly."},
    {"Crop": "Sesamum (Til)", "Type": "Oilseed", "Season": "Kharif/Summer", "N-P-K": "40:20:20", "Fertilizer": "Urea, SSP, MOP", "Soil": "Well-drained", "Water": "Low", "Pest": "Leaf Webber", "Harvesting": "Aug-Oct", "Pro-Tip": "Harvest when 75% capsules turn yellow to avoid shattering."},

    # --- PART 4: CASH & FIBER CROPS ---
    {"Crop": "Cotton", "Type": "Fiber", "Season": "Kharif", "N-P-K": "100:50:50", "Fertilizer": "DAP, Urea, Potash", "Soil": "Black Soil", "Water": "Moderate", "Pest": "Bollworm", "Harvesting": "Oct-Dec", "Pro-Tip": "Avoid high Nitrogen late in the season to prevent pest outbreaks."},
    {"Crop": "Sugarcane", "Type": "Cash Crop", "Season": "Annual", "N-P-K": "150:80:60", "Fertilizer": "Urea, SSP, MOP", "Soil": "Alluvial", "Water": "High", "Pest": "Top Borer", "Harvesting": "Dec-March", "Pro-Tip": "Use 'Setts' from top 1/3rd of the cane for better germination."},
    {"Crop": "Jute", "Type": "Fiber", "Season": "Kharif", "N-P-K": "40:20:20", "Fertilizer": "Urea, SSP", "Soil": "New Alluvial", "Water": "High", "Pest": "Semi-looper", "Harvesting": "July-Sept", "Pro-Tip": "Harvest at 'small pod' stage for best fiber strength."},
    {"Crop": "Tobacco", "Type": "Cash Crop", "Season": "Rabi", "N-P-K": "100:50:100", "Fertilizer": "Ammonium Sulphate", "Soil": "Light Sandy", "Water": "Moderate", "Pest": "Leaf Eater", "Harvesting": "Feb-March", "Pro-Tip": "Desuckering (removing side shoots) is vital for leaf quality."},

    # --- PART 5: FRUITS ---
    {"Crop": "Mango", "Type": "Fruit", "Season": "Perennial", "N-P-K": "100:50:100 (g/tree)", "Fertilizer": "NPK, Bone Meal", "Soil": "Deep Loam", "Water": "Moderate", "Pest": "Hopper", "Harvesting": "March-July", "Pro-Tip": "Do not irrigate during flowering to prevent flower drop."},
    {"Crop": "Banana", "Type": "Fruit", "Season": "Year-round", "N-P-K": "200:100:300", "Fertilizer": "Urea, MOP", "Soil": "Clay Loam", "Water": "High", "Pest": "Panama Wilt", "Harvesting": "12-15 Months", "Pro-Tip": "Remove male buds after last hand opens to increase fruit weight."},
    {"Crop": "Apple", "Type": "Fruit", "Season": "Perennial", "N-P-K": "700:350:700", "Fertilizer": "Urea, MOP", "Soil": "Loamy", "Water": "Moderate", "Pest": "Scale", "Harvesting": "Aug-Oct", "Pro-Tip": "Requires 'chilling hours' below 7°C to break dormancy."},
    {"Crop": "Grapes", "Type": "Fruit", "Season": "Perennial", "N-P-K": "500:500:1000", "Fertilizer": "Potash, DAP", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Downy Mildew", "Harvesting": "Jan-April", "Pro-Tip": "Pruning twice a year is mandatory for fruiting."},
    {"Crop": "Pomegranate", "Type": "Fruit", "Season": "Perennial", "N-P-K": "625:250:250", "Fertilizer": "FYM, NPK", "Soil": "Sandy", "Water": "Low", "Pest": "Butterfly", "Harvesting": "5-6 Months", "Pro-Tip": "Regulation of 'Bahar' (flowering) is key to year-round income."},
    {"Crop": "Guava", "Type": "Fruit", "Season": "Perennial", "N-P-K": "600:400:400", "Fertilizer": "Urea, SSP", "Soil": "Alluvial", "Water": "Low", "Pest": "Fruit Fly", "Harvesting": "Aug-Jan", "Pro-Tip": "Training and pruning keep the tree reachable and productive."},
    {"Crop": "Papaya", "Type": "Fruit", "Season": "Annual", "N-P-K": "250:250:500", "Fertilizer": "NPK, Boron", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Ring Spot Virus", "Harvesting": "10-12 Months", "Pro-Tip": "Avoid water stagnation near the trunk to prevent stem rot."},

    # --- PART 6: VEGETABLES & SPICES ---
    {"Crop": "Potato", "Type": "Vegetable", "Season": "Rabi", "N-P-K": "120:100:120", "Fertilizer": "CAN, DAP, MOP", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Blight", "Harvesting": "Jan-March", "Pro-Tip": "De-haulming 10 days before harvest thickens tuber skin."},
    {"Crop": "Onion", "Type": "Vegetable", "Season": "Rabi/Kharif", "N-P-K": "100:50:80", "Fertilizer": "Urea, Potash", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Thrips", "Harvesting": "March-May", "Pro-Tip": "Stop irrigation 15 days before harvest for longer storage."},
    {"Crop": "Tomato", "Type": "Vegetable", "Season": "Year-round", "N-P-K": "100:80:60", "Fertilizer": "DAP, Calcium", "Soil": "Loam", "Water": "Moderate", "Pest": "Fruit Borer", "Harvesting": "60-70 Days", "Pro-Tip": "Staking prevents fruit rot and improves air circulation."},
    {"Crop": "Chilli", "Type": "Spice", "Season": "Kharif/Rabi", "N-P-K": "100:60:60", "Fertilizer": "FYM, Urea", "Soil": "Black/Loamy", "Water": "Moderate", "Pest": "Mites", "Harvesting": "Multiple", "Pro-Tip": "Spray Neem oil regularly to control leaf curling."},
    {"Crop": "Garlic", "Type": "Spice", "Season": "Rabi", "N-P-K": "100:50:50", "Fertilizer": "Ammonium Sulphate", "Soil": "Rich Loam", "Water": "Moderate", "Pest": "Thrips", "Harvesting": "130-150 Days", "Pro-Tip": "Curing in shade for 7-10 days is essential for shelf life."},
    {"Crop": "Ginger", "Type": "Spice", "Season": "Annual", "N-P-K": "75:50:50", "Fertilizer": "FYM, Urea", "Soil": "Sandy Loam", "Water": "High", "Pest": "Soft Rot", "Harvesting": "Dec-Feb", "Pro-Tip": "Earthing up prevents rhizome exposure to sun."},
    {"Crop": "Turmeric", "Type": "Spice", "Season": "Annual", "N-P-K": "60:60:120", "Fertilizer": "FYM, MOP", "Soil": "Sandy Loam", "Water": "High", "Pest": "Rhizome Rot", "Harvesting": "Jan-March", "Pro-Tip": "Mulching with green leaves helps moisture retention."},

    # --- PART 7: MILLETS & MEDICINAL ---
    {"Crop": "Bajra (Pearl Millet)", "Type": "Millet", "Season": "Kharif", "N-P-K": "80:40:40", "Fertilizer": "Urea, DAP", "Soil": "Sandy", "Water": "Very Low", "Pest": "Ergot", "Harvesting": "Oct-Nov", "Pro-Tip": "Highly drought-tolerant; avoid water during flowering."},
    {"Crop": "Ragi (Finger Millet)", "Type": "Millet", "Season": "Kharif", "N-P-K": "60:30:30", "Fertilizer": "Urea, SSP", "Soil": "Red/Sandy", "Water": "Low", "Pest": "Blast", "Harvesting": "Oct-Nov", "Pro-Tip": "Extremely rich in Calcium; thrives in dry conditions."},
    {"Crop": "Sorghum (Jowar)", "Type": "Millet", "Season": "Kharif/Rabi", "N-P-K": "80:40:40", "Fertilizer": "Urea, DAP", "Soil": "Heavy/Black", "Water": "Low", "Pest": "Shoot Fly", "Harvesting": "Oct-March", "Pro-Tip": "Avoid feeding young green plants to cattle (HCN risk)."},
    {"Crop": "Ashwagandha", "Type": "Medicinal", "Season": "Late Kharif", "N-P-K": "15:20:0", "Fertilizer": "Vermicompost", "Soil": "Sandy Loam", "Water": "Low", "Pest": "Mites", "Harvesting": "150-180 Days", "Pro-Tip": "Avoid waterlogging; roots rot easily in wet soil."},
    {"Crop": "Mentha (Mint)", "Type": "Aromatic", "Season": "Summer", "N-P-K": "120:50:40", "Fertilizer": "Urea, SSP", "Soil": "Deep Loam", "Water": "High", "Pest": "Termites", "Harvesting": "100-120 Days", "Pro-Tip": "First harvest at 100 days; others every 60 days."},

    # --- PART 8: EXOTIC & REMAINING ---
    {"Crop": "Walnut", "Type": "Dry Fruit", "Season": "Perennial", "N-P-K": "100:50:50", "Fertilizer": "FYM, Urea", "Soil": "Silt Loam", "Water": "Moderate", "Pest": "Moth", "Harvesting": "Sept-Oct", "Pro-Tip": "Roots release 'juglone' which can inhibit other plants."},
    {"Crop": "Strawberry", "Type": "Fruit", "Season": "Rabi", "N-P-K": "80:40:40", "Fertilizer": "NPK, Boron", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Mite", "Harvesting": "Feb-April", "Pro-Tip": "Black plastic mulching prevents fruit rot."},
    {"Crop": "Black Pepper", "Type": "Spice", "Season": "Perennial", "N-P-K": "100:40:140", "Fertilizer": "NPK, Neem Cake", "Soil": "Red Laterite", "Water": "High", "Pest": "Quick Wilt", "Harvesting": "Dec-Jan", "Pro-Tip": "Requires 50% shade and support-trees like Silver Oak."},
    {"Crop": "Cardamom", "Type": "Spice", "Season": "Perennial", "N-P-K": "75:75:150", "Fertilizer": "Bone Meal", "Soil": "Forest Loam", "Water": "High", "Pest": "Thrips", "Harvesting": "Aug-Feb", "Pro-Tip": "Thrives in high humidity and filtered sunlight."},
    {"Crop": "Coconut", "Type": "Plantation", "Season": "Perennial", "N-P-K": "500:320:1200", "Fertilizer": "MOP, Urea", "Soil": "Coastal Sandy", "Water": "High", "Pest": "Beetle", "Harvesting": "60 Days", "Pro-Tip": "Apply salt to basin to improve nut size."},
    {"Crop": "Rubber", "Type": "Commercial", "Season": "Perennial", "N-P-K": "30:30:30", "Fertilizer": "Rock Phosphate", "Soil": "Laterite", "Water": "High", "Pest": "Mildew", "Harvesting": "6-7 Years", "Pro-Tip": "Early morning tapping gives the best latex flow."},
    {"Crop": "Cumin (Jeera)", "Type": "Spice", "Season": "Rabi", "N-P-K": "30:20:0", "Fertilizer": "Urea, DAP", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Wilt", "Harvesting": "Feb-March", "Pro-Tip": "Sensitive to moisture; avoid watering in cloudy weather."},
    {"Crop": "Safflower", "Type": "Oilseed", "Season": "Rabi", "N-P-K": "40:40:20", "Fertilizer": "Urea, SSP", "Soil": "Black Cotton", "Water": "Low", "Pest": "Aphids", "Harvesting": "March-April", "Pro-Tip": "Deep taproot makes it highly drought-resistant."},
    {"Crop": "Coffee", "Type": "Plantation", "Season": "Perennial", "N-P-K": "160:120:160", "Fertilizer": "Urea, MOP", "Soil": "Laterite", "Water": "High", "Pest": "Borer", "Harvesting": "Nov-Feb", "Pro-Tip": "Requires shade trees to protect from direct hot sun."},
    {"Crop": "Tea", "Type": "Plantation", "Season": "Perennial", "N-P-K": "120:60:60", "Fertilizer": "NPK, Urea", "Soil": "Acidic", "Water": "High", "Pest": "Mosquito Bug", "Harvesting": "Frequent", "Pro-Tip": "Maintain soil pH 4.5 to 5.5 for best quality."},
    {"Crop": "Jackfruit", "Type": "Fruit", "Season": "Perennial", "N-P-K": "1:1:1", "Fertilizer": "Organic, NPK", "Soil": "Alluvial", "Water": "Low", "Pest": "Borer", "Harvesting": "March-June", "Pro-Tip": "Thinning small fruits helps remaining ones grow larger."},
    {"Crop": "Custard Apple", "Type": "Fruit", "Season": "Annual", "N-P-K": "250:125:125", "Fertilizer": "FYM, Urea", "Soil": "Sandy Loam", "Water": "Low", "Pest": "Mealybug", "Harvesting": "Oct-Dec", "Pro-Tip": "Hand pollination can increase fruit set in dry areas."},
    {"Crop": "Marigold", "Type": "Flower", "Season": "Year-round", "N-P-K": "100:100:100", "Fertilizer": "NPK", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Borer", "Harvesting": "60-70 Days", "Pro-Tip": "Pinch terminal buds at 40 days for more branches."},
    {"Crop": "Rose", "Type": "Flower", "Season": "Perennial", "N-P-K": "10:20:10", "Fertilizer": "Bone Meal", "Soil": "Clayey", "Water": "Moderate", "Pest": "Die-back", "Harvesting": "Multiple", "Pro-Tip": "October pruning is essential for new flowering shoots."},
    {"Crop": "Buckwheat", "Type": "Pseudo-cereal", "Season": "Rabi", "N-P-K": "40:20:20", "Fertilizer": "DAP", "Soil": "Acidic", "Water": "Moderate", "Pest": "Aphids", "Harvesting": "70-90 Days", "Pro-Tip": "Gluten-free and improves soil for future crops."},
    {"Crop": "Cauliflower", "Type": "Vegetable", "Season": "Rabi", "N-P-K": "120:60:60", "Fertilizer": "Urea, SSP, Boron", "Soil": "Loamy", "Water": "Moderate", "Pest": "Diamondback Moth", "Harvesting": "90-120 Days", "Pro-Tip": "Blanching (covering the curd with leaves) keeps the cauliflower white and tender."},
    {"Crop": "Cabbage", "Type": "Vegetable", "Season": "Rabi", "N-P-K": "150:80:100", "Fertilizer": "DAP, MOP, Urea", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Aphids", "Harvesting": "80-100 Days", "Pro-Tip": "Maintain consistent moisture to prevent head cracking."},
    {"Crop": "Brinjal (Eggplant)", "Type": "Vegetable", "Season": "Year-round", "N-P-K": "100:50:50", "Fertilizer": "FYM, Urea", "Soil": "Silt Loam", "Water": "Moderate", "Pest": "Shoot Borer", "Harvesting": "120-150 Days", "Pro-Tip": "Regular picking of mature fruits encourages the plant to produce more."},
    {"Crop": "Okra (Bhindi)", "Type": "Vegetable", "Season": "Kharif/Summer", "N-P-K": "100:50:50", "Fertilizer": "Urea, DAP", "Soil": "Alluvial", "Water": "Moderate", "Pest": "Fruit Borer", "Harvesting": "45-60 Days", "Pro-Tip": "Soaking seeds in water for 24 hours improves the germination rate significantly."},
    {"Crop": "Peas", "Type": "Vegetable/Pulse", "Season": "Rabi", "N-P-K": "40:60:40", "Fertilizer": "DAP, MOP", "Soil": "Well-drained Loam", "Water": "Moderate", "Pest": "Powdery Mildew", "Harvesting": "60-90 Days", "Pro-Tip": "Harvest in the morning when sugar content is highest for better taste."},
    {"Crop": "Pear", "Type": "Fruit", "Season": "Perennial", "N-P-K": "600:300:600 (g/tree)", "Fertilizer": "Urea, MOP", "Soil": "Deep Loam", "Water": "Moderate", "Pest": "Codling Moth", "Harvesting": "July-Sept", "Pro-Tip": "Pears are best picked while still firm; they ripen perfectly off the tree."},
    {"Crop": "Peach", "Type": "Fruit", "Season": "Perennial", "N-P-K": "500:250:500 (g/tree)", "Fertilizer": "NPK Mixture", "Soil": "Sandy Loam", "Water": "Moderate", "Pest": "Leaf Curl", "Harvesting": "May-July", "Pro-Tip": "Thinning the fruit (leaving 6 inches between peaches) ensures larger, sweeter fruit."},
    {"Crop": "Plum", "Type": "Fruit", "Season": "Perennial", "N-P-K": "400:200:400 (g/tree)", "Fertilizer": "Urea, Potash", "Soil": "Well-drained", "Water": "Moderate", "Pest": "Aphids", "Harvesting": "June-August", "Pro-Tip": "Pruning in winter helps maintain a strong structure for heavy fruit loads."},
    {"Crop": "Almond", "Type": "Dry Fruit", "Season": "Perennial", "N-P-K": "500:250:700 (g/tree)", "Fertilizer": "Urea, MOP", "Soil": "Deep Loamy", "Water": "Low", "Pest": "Mites", "Harvesting": "August-Sept", "Pro-Tip": "Almonds require cross-pollination; plant at least two different varieties near each other."},
    {"Crop": "Litchi", "Type": "Fruit", "Season": "Perennial", "N-P-K": "600:400:600 (g/tree)", "Fertilizer": "FYM, NPK", "Soil": "Deep Alluvial", "Water": "High", "Pest": "Mite", "Harvesting": "May-June", "Pro-Tip": "Avoid irrigation during fruit ripening to prevent fruit cracking."},

    # --- PART 10: AGROFORESTRY & MEDICINAL ---
    {"Crop": "Pine", "Type": "Timber", "Season": "Perennial", "N-P-K": "100:50:50", "Fertilizer": "Organic Mulch", "Soil": "Acidic/Sandy", "Water": "Moderate", "Pest": "Bark Beetle", "Harvesting": "15-20 Years", "Pro-Tip": "Excellent for preventing soil erosion on hilly slopes."},
    {"Crop": "Bamboo", "Type": "Commercial", "Season": "Perennial", "N-P-K": "100:50:50", "Fertilizer": "Urea, FYM", "Soil": "Alluvial/Loamy", "Water": "High", "Pest": "Bamboo Borer", "Harvesting": "3-5 Years", "Pro-Tip": "Considered 'Green Gold' due to its fast growth and multi-purpose use."},
    {"Crop": "Teak", "Type": "Timber", "Season": "Perennial", "N-P-K": "200:100:100", "Fertilizer": "NPK, FYM", "Soil": "Deep Alluvial", "Water": "Moderate", "Pest": "Defoliator", "Harvesting": "20-25 Years", "Pro-Tip": "Pruning side branches early ensures a straight, high-quality timber log."},
    {"Crop": "Neem", "Type": "Medicinal/Timber", "Season": "Perennial", "N-P-K": "Low Requirement", "Fertilizer": "Organic Matter", "Soil": "Almost Any", "Water": "Very Low", "Pest": "Scale Insect", "Harvesting": "5-7 Years", "Pro-Tip": "Neem acts as a natural pesticide; planting it near other crops reduces pest pressure."},
    {"Crop": "Aloe Vera", "Type": "Medicinal", "Season": "Year-round", "N-P-K": "20:20:20", "Fertilizer": "Liquid Fertilizer", "Soil": "Sandy", "Water": "Very Low", "Pest": "Mealybug", "Harvesting": "6-8 Months", "Pro-Tip": "Harvest only the outermost leaves to allow the inner plant to keep growing."}
   
]
